### ISSUE TITLE
samizreal's checklist

### ISSUE THREAD

**Issue by samizreal** [githubschool/abracadabar#10]
- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request
- [x] Perform a peer review
- [x] Merge

**Comment by samizreal** [comment]
-[]Create an issue
  Create a branch
  Make changes to our file
  Make commits
  Make a pull request
  Perform a peer review
  Merge

**Comment by beardofedu** [comment]
- [ ] checklist 👍
