### ISSUE TITLE
SirDisney13's Checklist

### ISSUE THREAD

**Issue by SirDisney13** [githubschool/abracadabar#11]
During class I'm going to:

- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request
- [x] Perform a peer review
- [x] Merge
