### ISSUE TITLE
beardofedu's checklist

### ISSUE THREAD

**Issue by beardofedu** [githubschool/abracadabar#12]
During class I'm going to:

- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request 
- [x] Perform a peer review
- [x] Merge
