### ISSUE TITLE
JB's Checklist

### ISSUE THREAD

**Issue by barrj089** [githubschool/abracadabar#14]
During class I'm going to:

- [x] Create an issue
- [ ] Create a branch
- [ ] Make changes to our file
- [ ] Make commits
- [ ] Make a pull request 
- [ ] Perform a peer review
- [ ] Merge
