### ISSUE TITLE
bwsiewer's checklist

### ISSUE THREAD

**Issue by bwsiewer** [githubschool/abracadabar#15]
I am going to:

- [x] Create a issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request
- [x] Perform a peer review
- [x] Merge
