### ISSUE TITLE
dorinalora's checklist

### ISSUE THREAD

**Issue by dorinalora** [githubschool/abracadabar#7]
During class I'm going to:

- [ ]  Create an issue
- [ ]  Create a branch
- [ ]  Make changes to our file
- [ ]  Make commits
- [ ]  Make a pull request
- [ ]  Perform a peer review
- [ ]  Merge
