### ISSUE TITLE
GeoffreyGrike's checklist

### ISSUE THREAD

**Issue by GeoffreyGrike** [githubschool/abracadabar#8]

**Comment by GeoffreyGrike** [comment]
- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [ ] Make a pull request
- [ ] Perform a peer review
