### ISSUE TITLE
webbj62 checklist

### ISSUE THREAD

**Issue by webbj62** [githubschool/abracadabar#9]
During class I'm going to:  
- [x] Create an issue
- [x] Create a branch
- [x] Make changes to our file
- [x] Make commits
- [x] Make a pull request 
- [x] Perform a peer review
- [x] Merge
